//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_clientes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Negocios2020Entities : DbContext
    {
        public Negocios2020Entities()
            : base("name=Negocios2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Distritos> Distritos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<pedidoscabe> pedidoscabe { get; set; }
        public virtual DbSet<pedidosdeta> pedidosdeta { get; set; }
        public virtual DbSet<relacionvista> relacionvista { get; set; }
    
        public virtual ObjectResult<usp_Cargo_Listar_Result> usp_Cargo_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Cargo_Listar_Result>("usp_Cargo_Listar");
        }
    
        public virtual ObjectResult<usp_CargosListar_Result> usp_CargosListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CargosListar_Result>("usp_CargosListar");
        }
    
        public virtual ObjectResult<usp_Datos_Empleado_Result> usp_Datos_Empleado(Nullable<int> idEmpleado)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Datos_Empleado_Result>("usp_Datos_Empleado", idEmpleadoParameter);
        }
    
        public virtual ObjectResult<usp_Distrito_Listar_Result> usp_Distrito_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Distrito_Listar_Result>("usp_Distrito_Listar");
        }
    
        public virtual ObjectResult<usp_DistritoListar_Result> usp_DistritoListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DistritoListar_Result>("usp_DistritoListar");
        }
    
        public virtual int usp_Eliminar_Empleado(Nullable<int> idEmpleado)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Eliminar_Empleado", idEmpleadoParameter);
        }
    
        public virtual ObjectResult<usp_Empleado_Listar_Result> usp_Empleado_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Empleado_Listar_Result>("usp_Empleado_Listar");
        }
    
        public virtual ObjectResult<usp_EmpleadoListar_Result> usp_EmpleadoListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_EmpleadoListar_Result>("usp_EmpleadoListar");
        }
    
        public virtual int usp_Insertar_Empleado(string apeEmpleado, string nomEmpleado, Nullable<System.DateTime> fecNac, string dirEmpleado, Nullable<int> idDistrito, string fonoEmpleado, Nullable<int> idCargo, Nullable<System.DateTime> fecContrata)
        {
            var apeEmpleadoParameter = apeEmpleado != null ?
                new ObjectParameter("ApeEmpleado", apeEmpleado) :
                new ObjectParameter("ApeEmpleado", typeof(string));
    
            var nomEmpleadoParameter = nomEmpleado != null ?
                new ObjectParameter("NomEmpleado", nomEmpleado) :
                new ObjectParameter("NomEmpleado", typeof(string));
    
            var fecNacParameter = fecNac.HasValue ?
                new ObjectParameter("FecNac", fecNac) :
                new ObjectParameter("FecNac", typeof(System.DateTime));
    
            var dirEmpleadoParameter = dirEmpleado != null ?
                new ObjectParameter("DirEmpleado", dirEmpleado) :
                new ObjectParameter("DirEmpleado", typeof(string));
    
            var idDistritoParameter = idDistrito.HasValue ?
                new ObjectParameter("idDistrito", idDistrito) :
                new ObjectParameter("idDistrito", typeof(int));
    
            var fonoEmpleadoParameter = fonoEmpleado != null ?
                new ObjectParameter("fonoEmpleado", fonoEmpleado) :
                new ObjectParameter("fonoEmpleado", typeof(string));
    
            var idCargoParameter = idCargo.HasValue ?
                new ObjectParameter("idCargo", idCargo) :
                new ObjectParameter("idCargo", typeof(int));
    
            var fecContrataParameter = fecContrata.HasValue ?
                new ObjectParameter("FecContrata", fecContrata) :
                new ObjectParameter("FecContrata", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insertar_Empleado", apeEmpleadoParameter, nomEmpleadoParameter, fecNacParameter, dirEmpleadoParameter, idDistritoParameter, fonoEmpleadoParameter, idCargoParameter, fecContrataParameter);
        }
    
        public virtual ObjectResult<usp_ProductoListar_Result> usp_ProductoListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProductoListar_Result>("usp_ProductoListar");
        }
    }
}
